<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>musicApp.Updater.Swap</RootNamespace>
    <AssemblyName>musicApp-updater-swap</AssemblyName>
    <AssemblyTitle>musicApp Updater Swap</AssemblyTitle>
    <Product>musicApp</Product>
    <Company>musicApp</Company>
    <Platforms>portable;x64;x86;arm64</Platforms>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Platform)'=='portable'">
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Platform)'=='arm64'">
    <PlatformTarget>ARM64</PlatformTarget>
  </PropertyGroup>

</Project>
